(
SELECT CITY,
       LENGTH(CITY) AS CITY_LENGTH
  FROM STATION
ORDER BY CITY_LENGTH, CITY
LIMIT 1)

UNION

(
SELECT CITY,
       LENGTH(CITY) AS CITY_LENGTH
  FROM STATION
ORDER BY CITY_LENGTH DESC, CITY
LIMIT 1);